# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 14:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0003_auto_20170726_2006'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment_model',
            old_name='post_id',
            new_name='post',
        ),
    ]
